<?PHP
$index= "../m/header.php";
$home_contents_title1="<center><h1>Reports </h1><br><h3>Recent Contacts Sent</h3>";
$home_contents_title2=" <h3>Registered Clients</h3>";
$home_center_align="</center>";
$logout="<a href='../v1/logout.php'>Sign Out</a>";
$home="<a href='../v2/home.php?title=Home' class='w3-bar-item w3-button w3-padding'><b>Home</b></a>";  
$home="<a href='../v2/home.php?title=Home' class='w3-bar-item w3-button w3-padding'><b>Home</b></a>";  
$leads="<a href='../v2/leads.php' class='w3-bar-item w3-button w3-padding'><b>Leads</b></a>";
$clead='../v2/lead.php';
$ilead='../v2/ilead.php';
$lead_api="<a href='../v2/leads.php?title=Leads&item1=Create Lead&l=$clead&item2=Import Leads&li=$ilead' class='w3-bar-item w3-button w3-padding'><b>Leads</b></a>";
$lead_api2="<a href='../v2/leads.php?t=Leads&Create Lead&$lead&Import Leads&$ileads' class='w3-bar-item w3-button w3-padding'><b>Leads</b></a>";
$ileads="<a href='../v2/ilead.php' class='w3-bar-item w3-button w3-padding'>Import Leads</a>";
$lead="<a href='../v2/lead.php' class='w3-bar-item w3-button w3-padding'>Create Lead</a>";
$email_reports="<a href='../v2/email_rep.php' class='w3-bar-item w3-button w3-padding'><b>Automation</b></a>";
$email="<a href='../v2/email.php' class='w3-bar-item w3-button w3-padding'>Send Emails</a>";
$email_camp="<a href='../v2/email_camp.php' class='w3-bar-item w3-button w3-padding'><b>Campaigns</b></a>";
$email_group="<a href='../v2/email_group.php' class='w3-bar-item w3-button w3-padding'>Email Group</a>";
$sms_reports="<a href='/v2/sms_rep.php' class='w3-bar-item w3-button w3-padding'><b>SMS REPORTS</b></a>";
$sms="<a href='../v2/sms.php' class='w3-bar-item w3-button w3-padding'>Send SMS</a>";
$sms_camp="<a href='../v2/sms.php' class='w3-bar-item w3-button w3-padding'>SMS Campaign</a>";
$sms_group="<a href='../v2/sms.php' class='w3-bar-item w3-button w3-padding'>SMS Group</a>";
$icontacts="<a href='../v2/icontacts.php' class='w3-bar-item w3-button w3-padding'>Import Contacts</a>";
$contact="<a href='../v2/contact.php' class='w3-bar-item w3-button w3-padding'>Create Contact</a>";
$contacts="<a href='../v2/contacts.php?title=Contacts&item1=Create Contact&item2=Import Contacts' class='w3-bar-item w3-button w3-padding'><b>Contacts</b></a>";
$campaign="<a href='../v2/campaigns.php?title=Campaigns&item1=Create Campaign&item2=Manage Template' class='w3-bar-item w3-button w3-padding'><b>Campaigns</b></a>";
$reports="<a href='../v2/reports.php?title=Reports&item1=Campaigns Reports&item2=Operation Reports' class='w3-bar-item w3-button w3-padding'><b>Reports</b></a>";
$automation="<a href='../v2/automation.php?title=Automation&item1=Send Email&item2=Email Automation' class='w3-bar-item w3-button w3-padding'><b>Automation</b></a>";
$opportunities="<a href='../v2/automation.php?title=Opportunities&item1=Create Opportunity&item2=Import Opportunity' class='w3-bar-item w3-button w3-padding'><b>Opportunities</b></a>";
$contacts_ov="../c/contacts_overview.php";
$camp_ov="../c/camp_overview.php";
$leads_ov="../c/leads_overview.php";
$automation_ov="../c/automation_overview.php";
$pipeline="../c/pipeline.php";
$tasks="../c/tasks.php";
$list="../v2/list.php";
?>